# Generated by Django 3.2.12 on 2024-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='puplicada',
            field=models.BooleanField(default=False),
        ),
    ]
