# Generated by Django 3.2.12 on 2024-01-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_puplicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='puplicada',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
