# Generated by Django 4.1 on 2024-02-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
        ('galeria', '0006_alter_fotografia_foto'),
    ]

    operations = [
    ]
